name: build-release

on:
  workflow_dispatch:
  release:
    types: [prereleased, released]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-mac:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - name: Checkout source
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0

    - name: Build native packages
      run: ./.github/scripts/create_release.sh

    - name: Upload binaries to release
      run: gh release upload "$GITHUB_REF_NAME" my-explorer-release/my-explorer*.dmg my-explorer-release/SHA256SUMS.txt --repo "$GITHUB_REPOSITORY" --clobber
      env:
        GH_TOKEN: ${{ github.token }}
